### ISSUE TITLE
please provide updated documentation

### ISSUE THREAD

**Issue by mmdock** [namiml/nami-apple#16]
**Describe the bug**
iOS Documentation does not match actually code APIs needed

**To Reproduce**
Some Examples of inaccurate iOS  docs
First: 
https://docs.namiml.com/reference/login

Instead I needed to use Nami.setExternalIdentifier(externalIdentifier: String?, type: Nami.NamiExternalIdentifierType)

Second:
https://docs.namiml.com/reference/isloggedin
Instead I needed to use Nami.getExternalIdentifier() != nil

Third:
https://docs.namiml.com/reference/loggedinid
Instead I needed to use Nami.getExternalIdentifier

**Expected behavior**
I expected the documentation would match what I would need to implement.  Instead, I had to spend some time investigation documentation inaccuracies in order to discover where lived the coded I needed.

**Comment by namidan** [comment]
Fixed the versioning on the docs portal, which caused the confusion here.
