### ISSUE TITLE
https://www.github.com/namiml/nami-apple/tree/master/Podfile.example

### ISSUE THREAD

**Issue by FAIZFREADY** [namiml/nami-apple#3]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
import com.namiml.paywall.NamiPaywallManager import android.util.Log    const val LOG_TAG = "ExampleApp"    class ExampleActivity : AppCompatActivity() {      private fun onPaywallRaise(Activity activity) {     NamiPaywallManager.preparePaywallForDisplay { success, error ->       if (success) {         NamiPaywallManager.raisePaywall(activity)       } else {         Log.w(LOG_TAG, "preparePaywallForDisplay failed -> $error")       }     }   } }

**Comment by acantarero** [comment]
these are android code samples that do not apply to the apple sdk.
