### ISSUE TITLE
https://www.github.com/jmslau/perf-android-large/tree/gradle/.buckversion

### ISSUE THREAD

**Issue by FAIZFREADY** [namiml/nami-apple#4]
https://www.github.com/jmslau/perf-android-large/tree/gradle/.buckversionhttps://www.github.com/jmslau/perf-android-large/tree/gradle/.buckconfighttps://www.github.com/namiml/nami-apple/tree/master/Podfile.exampleimport com.namiml.paywall.NamiPaywallManager import android.util.Log    const val LOG_TAG = "ExampleApp"    class ExampleActivity : AppCompatActivity() {      private fun onPaywallRaise(Activity activity) {     NamiPaywallManager.preparePaywallForDisplay { success, error ->       if (success) {         NamiPaywallManager.raisePaywall(activity)       } else {         Log.w(LOG_TAG, "preparePaywallForDisplay failed -> $error")       }     }   } }

**Comment by acantarero** [comment]
the above comment is kotlin code from our android sample app.  does not apply to our apple sdk
